-- =============================================================
-- SISTEMA BRM - SCHEMA COMPLETO PARA NOVO PROJETO SUPABASE
-- =============================================================
-- Copiar este conteúdo no SQL Editor do Supabase e executar.
-- Mantém o conjunto de tabelas já usado pelo sistema de hospedagens,
-- gestão institucional, usuários e módulo de religiosos.

create extension if not exists pgcrypto;

-- =============================================================
-- 1) USUÁRIOS ADMINISTRATIVOS
-- =============================================================
create table if not exists public.usuarios (
  idusuarios uuid primary key default gen_random_uuid(),
  auth_user_id uuid,
  usu_nome text not null,
  usu_email text not null,
  usu_status text not null default 'Ativo' check (usu_status in ('Ativo', 'Inativo')),
  usu_acessos jsonb not null default '[]'::jsonb,
  usu_pref_opensidebar boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =============================================================
-- 2) CONFIGURAÇÕES E METADADOS DE HOSPEDAGENS
-- =============================================================
create table if not exists public.confighospedagens (
  idconfighospedagens bigint generated by default as identity primary key,
  chos_acolhida text,
  chos_ativar text default 'Sim' check (chos_ativar in ('Sim', 'Não', 'ativo', 'inativo')),
  chos_txtinativo text,
  chos_visiveis jsonb default '[]'::jsonb,
  chos_invisiveis jsonb default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mainhospedagem (
  idmainhospedagem bigint generated by default as identity primary key,
  main_motivo text,
  main_host text,
  main_seguranca text,
  main_porta text,
  main_remetente text,
  main_email text,
  main_senha text,
  main_mensagemtela text,
  main_mensagememail text,
  main_termos text,
  main_recibo_pessoal text,
  main_recibo_terceiros text,
  main_recibo_mensagem text,
  main_status text not null default 'Ativo' check (main_status in ('Ativo', 'Inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.modulos (
  idmodulos bigint generated by default as identity primary key,
  mod_nome text not null,
  mod_status text not null default 'Ativo' check (mod_status in ('Ativo', 'Inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hos_quartos (
  idhos_quartos bigint generated by default as identity primary key,
  hos_qua_nome text not null,
  hos_qua_status text not null default 'Ativo' check (hos_qua_status in ('Ativo', 'Inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.statushospedagem (
  idstatushospedagem bigint generated by default as identity primary key,
  sta_nome text not null,
  sta_status text not null default 'Ativo' check (sta_status in ('Ativo', 'Inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lavanderia (
  idlavanderia bigint generated by default as identity primary key,
  lav_servico text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =============================================================
-- 3) HOSPEDAGENS / INSCRIÇÕES
-- =============================================================
create table if not exists public.hospedagens (
  idhospedagens bigint generated by default as identity primary key,

  hos_categoria text,
  hos_nome text,
  hos_nascimento date,
  hos_cpfrg text,
  hos_email text,
  hos_telefone text,
  hos_telefoneemergencia text,
  hos_logradouro text,
  hos_numero text,
  hos_cep text,
  hos_bairro text,
  hos_cidade text,
  hos_estado text,
  hos_alergico text,
  hos_especifiquealergia text,
  hos_restricaoalimentar text,
  hos_especifiquerestricao text,
  hos_lavanderia text,
  hos_estadiamotivo bigint,
  hos_modulo bigint,
  hos_previsaochegada date,
  hos_previsaosaida date,
  hos_recibo text,
  hos_recnome text,
  hos_reccpfcnpj text,
  hos_reclogradouro text,
  hos_recnumero text,
  hos_reccep text,
  hos_recbairro text,
  hos_reccidade text,
  hos_recestado text,
  hos_termo text,
  hos_status bigint,
  hos_checkin timestamptz,
  hos_checkout timestamptz,
  hos_quarto bigint,
  hos_inscricao timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hospedagens
  add constraint fk_hospedagens_motivo
  foreign key (hos_estadiamotivo) references public.mainhospedagem(idmainhospedagem) on delete set null,
  add constraint fk_hospedagens_modulo
  foreign key (hos_modulo) references public.modulos(idmodulos) on delete set null,
  add constraint fk_hospedagens_status
  foreign key (hos_status) references public.statushospedagem(idstatushospedagem) on delete set null,
  add constraint fk_hospedagens_quarto
  foreign key (hos_quarto) references public.hos_quartos(idhos_quartos) on delete set null;

-- =============================================================
-- 4) INSTITUCIONAL - COMUNIDADES, OBRAS E RELIGIOSOS
-- =============================================================
create table if not exists public.comunidades (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  padroeiro text,
  data_fundacao date,
  superior_id uuid,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  telefone text,
  email text,
  status text not null default 'Ativo' check (status in ('Ativo', 'Inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.obras (
  id uuid primary key default gen_random_uuid(),
  comunidade_id uuid references public.comunidades(id) on delete set null,
  nome text not null,
  tipo text not null check (tipo in ('Casa de Retiro/Hospedagem', 'Paróquia', 'Colégio', 'Seminário', 'Obra Social', 'Outro')),
  permite_hospedagem boolean not null default false,
  cnpj text,
  responsavel_id uuid,
  cep text,
  logradouro text,
  numero text,
  bairro text,
  cidade text,
  estado text,
  telefone text,
  email text,
  status text not null default 'Ativa' check (status in ('Ativa', 'Inativa')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.religiosos (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid,
  origem_cadastro text default 'admin' check (origem_cadastro in ('admin', 'publico')),

  nome_civil text not null,
  nome_religioso text,
  grau text not null check (grau in ('Frater', 'Irmão', 'Diácono', 'Padre', 'Bispo')),
  data_nascimento date,
  local_nascimento text,
  municipio_nascimento text,
  estado_nascimento text,
  pais_nascimento text,
  nacionalidade text,

  cpf text,
  rg text,
  rg_orgao_expedidor text,
  rg_data_emissao date,
  titulo_eleitor text,
  pis text,
  cnh text,
  cnh_categoria text,
  passaporte text,

  comunidade_atual_id uuid references public.comunidades(id) on delete set null,
  obra_atual_id uuid references public.obras(id) on delete set null,
  email_institucional text,
  email_pessoal text,
  telefone_celular text,
  whatsapp text,

  pai_nome text,
  mae_nome text,
  contato_nome text,
  contato_parentesco text,
  contato_telefone text,

  batismo_data date,
  batismo_paroquia text,
  batismo_diocese text,
  batismo_cidade text,
  batismo_uf text,
  batismo_livro text,
  batismo_folha text,
  batismo_numero_registro text,
  batismo_celebrante text,
  batismo_observacoes text,

  primeira_eucaristia_data date,
  primeira_eucaristia_paroquia text,
  primeira_eucaristia_diocese text,
  primeira_eucaristia_cidade text,
  primeira_eucaristia_celebrante text,
  primeira_eucaristia_observacoes text,

  crisma_data date,
  crisma_paroquia text,
  crisma_diocese text,
  crisma_cidade text,
  crisma_celebrante text,
  crisma_livro text,
  crisma_folha text,
  crisma_numero_registro text,

  parroquia_origem text,
  diocese_origem text,
  grupo_movimento_pastoral text,
  promotor_vocacional text,
  historico_vocacional text,

  seminario_menor text,
  seminario_menor_cidade text,
  seminario_menor_ingresso date,
  seminario_menor_conclusao date,
  seminario_menor_formador text,

  propedeutico_seminario text,
  propedeutico_cidade text,
  propedeutico_ingresso date,
  propedeutico_conclusao date,
  propedeutico_formador text,

  postulantado_seminario text,
  postulantado_cidade text,
  postulantado_ingresso date,
  postulantado_conclusao date,
  mestre_postulantado text,

  noviciado_seminario text,
  noviciado_local text,
  noviciado_ingresso date,
  noviciado_termino date,
  mestre_noviciado text,

  primeira_profissao_data date,
  primeira_profissao_local text,
  primeira_profissao_celebrante text,

  votos_temporarios_1_data date,
  votos_temporarios_1_local text,
  votos_temporarios_1_celebrante text,
  votos_temporarios_2_data date,
  votos_temporarios_2_local text,
  votos_temporarios_2_celebrante text,
  votos_temporarios_3_data date,
  votos_temporarios_3_local text,
  votos_temporarios_3_celebrante text,

  votos_perpetuos_data date,
  votos_perpetuos_local text,
  votos_perpetuos_celebrante text,

  ministerio_palavra_data date,
  ministerio_palavra_local text,
  ministerio_palavra_celebrante text,
  ministerio_altar_data date,
  ministerio_altar_local text,
  ministerio_altar_celebrante text,
  acolitado_data date,
  acolitado_local text,
  acolitado_celebrante text,
  leitorado_data date,
  leitorado_local text,
  leitorado_celebrante text,
  diaconato_data date,
  diaconato_local text,
  diaconato_bispo_ordenante text,
  presbiterado_data date,
  presbiterado_local text,
  presbiterado_bispo_ordenante text,
  episcopado_data date,
  episcopado_local text,
  episcopado_bispo_ordenante text,

  ensino_medio_instituicao text,
  filosofia_instituicao text,
  teologia_instituicao text,
  graduacao_instituicao text,
  pos_graduacao_instituicao text,
  mestrado_instituicao text,
  doutorado_instituicao text,
  especializacao_instituicao text,
  cursos_livres text,
  formacao_permanente text,

  idioma_portugues text default 'Nível básico',
  idioma_espanhol text,
  idioma_italiano text,
  idioma_ingles text,
  idioma_alemao text,
  idioma_latim text,
  idioma_grego text,
  idioma_outros text,
  competencias text,

  historico_comunidades text,
  missoes text,
  servicos_congregacao text,
  servicos_igreja text,
  cargos_externos text,

  plano_saude text,
  numero_plano_saude text,
  local_plano_saude text,
  sus text,
  tipo_sanguineo text,
  fator_rh text,
  alergias text,
  medicamentos_continuos text,
  medico_responsavel text,
  contato_emergencia text,
  informacoes_clinicas text,
  cirurgias text,
  protese text,
  observacoes_saude text,

  status text not null default 'Ativo' check (status in ('Ativo', 'Em missão externa', 'Em estudos', 'Emérito', 'Falecido', 'Exclausurado')),
  status_cadastro text not null default 'Aprovado' check (status_cadastro in ('Em revisão', 'Aprovado', 'Arquivado')),
  consentimento_dados boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.religiosos_irmaos (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  nome text not null,
  data_nascimento date,
  estado_civil text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_contatos_familiares (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  nome text not null,
  parentesco text,
  contato_1 text,
  contato_2 text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_documentos (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  categoria text not null,
  nome_arquivo text,
  url_arquivo text,
  quem_cadastrou text,
  data_cadastro date default current_date,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_formacao_academica (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  categoria text not null,
  instituicao text,
  periodo text,
  cidade text,
  estado text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_idiomas (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  idioma text not null,
  nivel text,
  competencia text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_historico_comunidades (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  periodo_inicio date,
  periodo_fim date,
  instituicao text,
  funcao text,
  local text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_missoes_servicos (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  tipo text not null check (tipo in ('Missão', 'Serviço à Congregação', 'Serviço à Igreja', 'CNBB', 'Diocese', 'Organismo', 'Assessoria', 'Cargo externo')),
  instituicao text,
  funcao text,
  periodo text,
  local text,
  documento text,
  observacao text,
  created_at timestamptz not null default now()
);

create table if not exists public.religiosos_enderecos (
  id uuid primary key default gen_random_uuid(),
  religioso_id uuid not null references public.religiosos(id) on delete cascade,
  obra_id uuid references public.obras(id) on delete set null,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  pais text,
  celular text,
  telefone text,
  email text,
  whatsapp text,
  redes_sociais text,
  created_at timestamptz not null default now()
);

-- =============================================================
-- 5) ÍNDICES
-- =============================================================
create index if not exists idx_usuarios_auth_user_id on public.usuarios(auth_user_id);
create index if not exists idx_hospedagens_motivo on public.hospedagens(hos_estadiamotivo);
create index if not exists idx_hospedagens_modulo on public.hospedagens(hos_modulo);
create index if not exists idx_hospedagens_status on public.hospedagens(hos_status);
create index if not exists idx_obras_comunidade on public.obras(comunidade_id);
create index if not exists idx_religiosos_comunidade on public.religiosos(comunidade_atual_id);
create index if not exists idx_religiosos_obra on public.religiosos(obra_atual_id);
create index if not exists idx_religiosos_nome on public.religiosos(nome_civil);

-- =============================================================
-- 6) TRIGGERS PARA updated_at
-- =============================================================
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row execute function public.set_updated_at();

create trigger trg_confighospedagens_updated_at
before update on public.confighospedagens
for each row execute function public.set_updated_at();

create trigger trg_mainhospedagem_updated_at
before update on public.mainhospedagem
for each row execute function public.set_updated_at();

create trigger trg_modulos_updated_at
before update on public.modulos
for each row execute function public.set_updated_at();

create trigger trg_hos_quartos_updated_at
before update on public.hos_quartos
for each row execute function public.set_updated_at();

create trigger trg_statushospedagem_updated_at
before update on public.statushospedagem
for each row execute function public.set_updated_at();

create trigger trg_lavanderia_updated_at
before update on public.lavanderia
for each row execute function public.set_updated_at();

create trigger trg_hospedagens_updated_at
before update on public.hospedagens
for each row execute function public.set_updated_at();

create trigger trg_comunidades_updated_at
before update on public.comunidades
for each row execute function public.set_updated_at();

create trigger trg_obras_updated_at
before update on public.obras
for each row execute function public.set_updated_at();

create trigger trg_religiosos_updated_at
before update on public.religiosos
for each row execute function public.set_updated_at();

-- =============================================================
-- 7) POLÍTICAS BÁSICAS DE RLS
-- =============================================================
-- Ative o RLS no painel do Supabase para as tabelas relevantes
-- e use as policies abaixo como base inicial.

-- Exemplo para usuários administrativos:
-- alter table public.usuarios enable row level security;
-- create policy "usuarios_select_authenticated" on public.usuarios
-- for select using (auth.role() = 'authenticated');
-- create policy "usuarios_insert_authenticated" on public.usuarios
-- for insert with check (auth.role() = 'authenticated');
-- create policy "usuarios_update_authenticated" on public.usuarios
-- for update using (auth.role() = 'authenticated');
-- create policy "usuarios_delete_authenticated" on public.usuarios
-- for delete using (auth.role() = 'authenticated');

-- Exemplo para página pública de inscrições:
-- alter table public.hospedagens enable row level security;
-- create policy "hospedagens_insert_anon" on public.hospedagens
-- for insert with check (true);
-- create policy "hospedagens_select_authenticated" on public.hospedagens
-- for select using (auth.role() = 'authenticated');
-- create policy "hospedagens_update_authenticated" on public.hospedagens
-- for update using (auth.role() = 'authenticated');

-- Exemplo para tabela de configuração pública:
-- alter table public.confighospedagens enable row level security;
-- create policy "confighospedagens_select_anon" on public.confighospedagens
-- for select using (true);

-- Exemplo para páginas públicas de formulário religioso:
-- alter table public.obras enable row level security;
-- create policy "obras_select_anon" on public.obras for select using (true);
-- alter table public.religiosos enable row level security;
-- create policy "religiosos_insert_publico" on public.religiosos
-- for insert with check (true);
-- create policy "religiosos_select_authenticated" on public.religiosos
-- for select using (auth.role() = 'authenticated');

-- =============================================================
-- 8) DADOS INICIAIS BASE (opcional)
-- =============================================================
-- Inserções mínimas para o sistema funcionar sem depender de admin manual.
-- Ajuste conforme o seu cenário real.

insert into public.confighospedagens (
  chos_acolhida,
  chos_ativar,
  chos_txtinativo,
  chos_visiveis,
  chos_invisiveis
) values (
  'Seja bem-vindo(a)!',
  'Sim',
  'As inscrições estão temporariamente suspensas.',
  '[]'::jsonb,
  '[]'::jsonb
)
on conflict do nothing;

insert into public.mainhospedagem (
  main_motivo,
  main_mensagemtela,
  main_mensagememail,
  main_termos,
  main_status
) values (
  'Retiro de Formação',
  'Sua inscrição foi recebida com sucesso. Em breve entraremos em contato.',
  'Recebemos sua inscrição e em breve entraremos em contato.',
  'Eu aceito os termos e regulamentos da hospedagem.',
  'Ativo'
)
on conflict do nothing;

insert into public.modulos (mod_nome, mod_status) values
  ('Módulo 1', 'Ativo'),
  ('Módulo 2', 'Ativo')
on conflict do nothing;

insert into public.hos_quartos (hos_qua_nome, hos_qua_status) values
  ('Quarto 01', 'Ativo'),
  ('Quarto 02', 'Ativo')
on conflict do nothing;

insert into public.statushospedagem (sta_nome, sta_status) values
  ('Pendente', 'Ativo'),
  ('Confirmada', 'Ativo'),
  ('Check-in', 'Ativo'),
  ('Check-out', 'Ativo')
on conflict do nothing;

insert into public.lavanderia (lav_servico) values
  ('Preciso de lavanderia'),
  ('Não preciso de lavanderia')
on conflict do nothing;
