-- =====================================================================
-- SISTEMA BRM (PROVÍNCIA BRASIL MERIDIONAL - SCJ)
-- SCRIPT SQL UNIFICADO COMPLETO PARA SUPABASE (BANCO DE DADOS)
-- =====================================================================
-- Instruções:
-- 1. Acesse o painel do Supabase (https://app.supabase.com)
-- 2. Selecione o seu projeto -> Clique em "SQL Editor" na barra lateral.
-- 3. Clique em "New Query" (+ Nova Consulta).
-- 4. Copie todo este conteúdo, cole no editor do Supabase e clique em "RUN".
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================
-- PARTE 1: TABELAS BASE, USUÁRIOS E HOSPEDARIA
-- =============================================================

CREATE TABLE IF NOT EXISTS public.usuarios (
  idusuarios uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid,
  usu_nome text NOT NULL,
  usu_email text NOT NULL,
  usu_status text NOT NULL DEFAULT 'Ativo' CHECK (usu_status IN ('Ativo', 'Inativo')),
  usu_acessos jsonb NOT NULL DEFAULT '[]'::jsonb,
  usu_pref_opensidebar boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.confighospedagens (
  idconfighospedagens bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chos_acolhida text,
  chos_ativar text DEFAULT 'Sim' CHECK (chos_ativar IN ('Sim', 'Não', 'ativo', 'inativo')),
  chos_txtinativo text,
  chos_visiveis jsonb DEFAULT '[]'::jsonb,
  chos_invisiveis jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mainhospedagem (
  idmainhospedagem bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  main_motivo text,
  main_host text,
  main_seguranca text,
  main_porta text,
  main_remetente text,
  main_email text,
  main_senha text,
  main_mensagemtela text,
  main_mensagememail text,
  main_termos text,
  main_recibo_pessoal text,
  main_recibo_terceiros text,
  main_recibo_mensagem text,
  main_status text NOT NULL DEFAULT 'Ativo' CHECK (main_status IN ('Ativo', 'Inativo')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.modulos (
  idmodulos bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mod_nome text NOT NULL,
  mod_status text NOT NULL DEFAULT 'Ativo' CHECK (mod_status IN ('Ativo', 'Inativo')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hos_quartos (
  idhos_quartos bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hos_qua_nome text NOT NULL,
  hos_qua_status text NOT NULL DEFAULT 'Ativo' CHECK (hos_qua_status IN ('Ativo', 'Inativo')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.statushospedagem (
  idstatushospedagem bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sta_nome text NOT NULL,
  sta_status text NOT NULL DEFAULT 'Ativo' CHECK (sta_status IN ('Ativo', 'Inativo')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lavanderia (
  idlavanderia bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lav_servico text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hospedagens (
  idhospedagens bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hos_categoria text,
  hos_nome text,
  hos_nascimento date,
  hos_cpfrg text,
  hos_email text,
  hos_telefone text,
  hos_telefoneemergencia text,
  hos_logradouro text,
  hos_numero text,
  hos_cep text,
  hos_bairro text,
  hos_cidade text,
  hos_estado text,
  hos_alergico text,
  hos_especifiquealergia text,
  hos_restricaoalimentar text,
  hos_especifiquerestricao text,
  hos_lavanderia text,
  hos_estadiamotivo bigint,
  hos_modulo bigint,
  hos_previsaochegada date,
  hos_previsaosaida date,
  hos_recibo text,
  hos_recnome text,
  hos_reccpfcnpj text,
  hos_reclogradouro text,
  hos_recnumero text,
  hos_reccep text,
  hos_recbairro text,
  hos_reccidade text,
  hos_recestado text,
  hos_termo text,
  hos_status bigint,
  hos_checkin timestamptz,
  hos_checkout timestamptz,
  hos_quarto bigint,
  hos_casa_acolhida text,
  hos_inscricao timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================
-- PARTE 2: INSTITUCIONAL - COMUNIDADES, OBRAS E RELIGIOSOS
-- =============================================================

CREATE TABLE IF NOT EXISTS public.comunidades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  padroeiro text,
  data_fundacao date,
  superior_id uuid,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  telefone text,
  email text,
  status text NOT NULL DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Inativo')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.obras (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  comunidade_id uuid REFERENCES public.comunidades(id) ON DELETE SET NULL,
  nome text NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('Casa de Retiro/Hospedagem', 'Paróquia', 'Colégio', 'Seminário', 'Obra Social', 'Outro')),
  permite_hospedagem boolean NOT NULL DEFAULT false,
  cnpj text,
  responsavel_id uuid,
  cep text,
  logradouro text,
  numero text,
  bairro text,
  cidade text,
  estado text,
  telefone text,
  email text,
  status text NOT NULL DEFAULT 'Ativa' CHECK (status IN ('Ativa', 'Inativa')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_obras_referencia (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  tipo text,
  cidade text,
  localidade text,
  uf text,
  email text,
  telefone text,
  diocese text,
  fundacao date,
  assumida_pelos_dehonianos date,
  endereco text,
  instagram text,
  facebook text,
  youtube text,
  site text,
  status text DEFAULT 'Ativa',
  token_edicao uuid DEFAULT gen_random_uuid(),
  historia text,
  resumo_historico text,
  fotos jsonb DEFAULT '[]'::jsonb,
  status_historia text DEFAULT 'Pendente',
  data_envio_historia timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT unq_obras_ref UNIQUE (nome, localidade, uf)
);

CREATE TABLE IF NOT EXISTS public.religiosos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid,
  origem_cadastro text DEFAULT 'admin' CHECK (origem_cadastro IN ('admin', 'publico')),
  nome_civil text NOT NULL,
  nome_religioso text,
  grau text NOT NULL CHECK (grau IN ('Frater', 'Irmão', 'Diácono', 'Padre', 'Bispo')),
  data_nascimento date,
  local_nascimento text,
  municipio_nascimento text,
  estado_nascimento text,
  pais_nascimento text,
  nacionalidade text,
  cpf text,
  rg text,
  rg_orgao_expedidor text,
  rg_data_emissao date,
  titulo_eleitor text,
  pis text,
  cnh text,
  cnh_categoria text,
  passaporte text,
  comunidade_atual_id uuid REFERENCES public.comunidades(id) ON DELETE SET NULL,
  obra_atual_id uuid REFERENCES public.obras(id) ON DELETE SET NULL,
  email_institucional text,
  email_pessoal text,
  telefone_celular text,
  whatsapp text,
  pai_nome text,
  mae_nome text,
  contato_nome text,
  contato_parentesco text,
  contato_telefone text,
  batismo_data date,
  batismo_paroquia text,
  batismo_diocese text,
  batismo_cidade text,
  batismo_uf text,
  batismo_livro text,
  batismo_folha text,
  batismo_numero_registro text,
  batismo_celebrante text,
  batismo_observacoes text,
  primeira_eucaristia_data date,
  primeira_eucaristia_paroquia text,
  primeira_eucaristia_diocese text,
  primeira_eucaristia_cidade text,
  primeira_eucaristia_celebrante text,
  primeira_eucaristia_observacoes text,
  crisma_data date,
  crisma_paroquia text,
  crisma_diocese text,
  crisma_cidade text,
  crisma_celebrante text,
  crisma_livro text,
  crisma_folha text,
  crisma_numero_registro text,
  parroquia_origem text,
  diocese_origem text,
  grupo_movimento_pastoral text,
  promotor_vocacional text,
  historico_vocacional text,
  seminario_menor text,
  seminario_menor_cidade text,
  seminario_menor_ingresso date,
  seminario_menor_conclusao date,
  seminario_menor_formador text,
  propedeutico_seminario text,
  propedeutico_cidade text,
  propedeutico_ingresso date,
  propedeutico_conclusao date,
  propedeutico_formador text,
  postulantado_seminario text,
  postulantado_cidade text,
  postulantado_ingresso date,
  postulantado_conclusao date,
  mestre_postulantado text,
  noviciado_seminario text,
  noviciado_local text,
  noviciado_ingresso date,
  noviciado_termino date,
  mestre_noviciado text,
  primeira_profissao_data date,
  primeira_profissao_local text,
  primeira_profissao_celebrante text,
  votos_temporarios_1_data date,
  votos_temporarios_1_local text,
  votos_temporarios_1_celebrante text,
  votos_temporarios_2_data date,
  votos_temporarios_2_local text,
  votos_temporarios_2_celebrante text,
  votos_temporarios_3_data date,
  votos_temporarios_3_local text,
  votos_temporarios_3_celebrante text,
  votos_perpetuos_data date,
  votos_perpetuos_local text,
  votos_perpetuos_celebrante text,
  ministerio_palavra_data date,
  ministerio_palavra_local text,
  ministerio_palavra_celebrante text,
  ministerio_altar_data date,
  ministerio_altar_local text,
  ministerio_altar_celebrante text,
  acolitado_data date,
  acolitado_local text,
  acolitado_celebrante text,
  leitorado_data date,
  leitorado_local text,
  leitorado_celebrante text,
  diaconato_data date,
  diaconato_local text,
  diaconato_bispo_ordenante text,
  presbiterado_data date,
  presbiterado_local text,
  presbiterado_bispo_ordenante text,
  episcopado_data date,
  episcopado_local text,
  episcopado_bispo_ordenante text,
  ensino_medio_instituicao text,
  filosofia_instituicao text,
  teologia_instituicao text,
  graduacao_instituicao text,
  pos_graduacao_instituicao text,
  mestrado_instituicao text,
  doutorado_instituicao text,
  especializacao_instituicao text,
  cursos_livres text,
  formacao_permanente text,
  idioma_portugues text DEFAULT 'Nível básico',
  idioma_espanhol text,
  idioma_italiano text,
  idioma_ingles text,
  idioma_alemao text,
  idioma_latim text,
  idioma_grego text,
  idioma_outros text,
  competencias text,
  historico_comunidades text,
  missoes text,
  servicos_congregacao text,
  servicos_igreja text,
  cargos_externos text,
  plano_saude text,
  numero_plano_saude text,
  local_plano_saude text,
  sus text,
  tipo_sanguineo text,
  fator_rh text,
  alergias text,
  medicamentos_continuos text,
  medico_responsavel text,
  contato_emergencia text,
  informacoes_clinicas text,
  cirurgias text,
  protese text,
  observacoes_saude text,
  status text NOT NULL DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Em missão externa', 'Em estudos', 'Emérito', 'Falecido', 'Exclausurado')),
  status_cadastro text NOT NULL DEFAULT 'Aprovado' CHECK (status_cadastro IN ('Em revisão', 'Aprovado', 'Arquivado')),
  consentimento_dados boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Subtabelas de Religiosos
CREATE TABLE IF NOT EXISTS public.religiosos_irmaos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  nome text NOT NULL,
  data_nascimento date,
  estado_civil text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_contatos_familiares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  nome text NOT NULL,
  parentesco text,
  contato_1 text,
  contato_2 text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_documentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  categoria text NOT NULL,
  nome_arquivo text,
  url_arquivo text,
  quem_cadastrou text,
  data_cadastro date DEFAULT current_date,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_formacao_academica (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  categoria text NOT NULL,
  instituicao text,
  periodo text,
  cidade text,
  estado text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_idiomas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  idioma text NOT NULL,
  nivel text,
  competencia text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_historico_comunidades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  periodo_inicio date,
  periodo_fim date,
  instituicao text,
  funcao text,
  local text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_missoes_servicos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  tipo text NOT NULL CHECK (tipo IN ('Missão', 'Serviço à Congregação', 'Serviço à Igreja', 'CNBB', 'Diocese', 'Organismo', 'Assessoria', 'Cargo externo')),
  instituicao text,
  funcao text,
  periodo text,
  local text,
  documento text,
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.religiosos_enderecos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  religioso_id uuid NOT NULL REFERENCES public.religiosos(id) ON DELETE CASCADE,
  obra_id uuid REFERENCES public.obras(id) ON DELETE SET NULL,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  pais text,
  celular text,
  telefone text,
  email text,
  whatsapp text,
  redes_sociais text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================
-- PARTE 3: SECRETARIA PROVINCIAL, FORMULÁRIOS E AGENDA
-- =============================================================

CREATE TABLE IF NOT EXISTS public.documentos_provinciais (
  id text PRIMARY KEY DEFAULT ('doc-' || substr(gen_random_uuid()::text, 1, 8)),
  titulo text NOT NULL,
  categoria text NOT NULL,
  subtitulo text,
  numero_referencia text,
  data_documento date NOT NULL DEFAULT current_date,
  arquivo_nome text NOT NULL,
  arquivo_url text NOT NULL,
  arquivo_path text,
  arquivo_tamanho_bytes bigint,
  mime_type text DEFAULT 'application/pdf',
  descricao text,
  publicado_por text DEFAULT 'Secretaria Provincial',
  status text NOT NULL DEFAULT 'Ativo',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.eventos_provinciais (
  id text PRIMARY KEY DEFAULT ('evt-' || substr(gen_random_uuid()::text, 1, 8)),
  titulo text NOT NULL,
  tipo text NOT NULL,
  data_inicio date NOT NULL,
  data_fim date,
  horario text,
  local text NOT NULL,
  cidade text,
  uf text,
  descricao text,
  publico_alvo text DEFAULT 'Toda a Província',
  status text NOT NULL DEFAULT 'Confirmado',
  exige_inscricao boolean NOT NULL DEFAULT false,
  formulario_id text,
  limite_vagas integer,
  prazo_inscricao date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.secretaria_configuracoes (
  id text PRIMARY KEY DEFAULT 'default-secretaria-cfg',
  prefixo_decretos text NOT NULL DEFAULT 'DEC-BRM',
  numero_atual_decretos integer NOT NULL DEFAULT 14,
  prefixo_portarias text NOT NULL DEFAULT 'PORT-BRM',
  numero_atual_portarias integer NOT NULL DEFAULT 8,
  prefixo_circulares text NOT NULL DEFAULT 'CIRC-BRM',
  numero_atual_circulares integer NOT NULL DEFAULT 5,
  prefixo_formularios text NOT NULL DEFAULT 'FORM-BRM',
  numero_atual_formularios integer NOT NULL DEFAULT 3,
  cabecalho_institucional text NOT NULL DEFAULT 'CONGREGAÇÃO DOS PADRES DO SAGRADO CORAÇÃO DE JESUS',
  subtitulo_provincia text NOT NULL DEFAULT 'PROVÍNCIA BRASIL MERIDIONAL (SCJ) • CURIA PROVINCIAL',
  orgao_emissor text NOT NULL DEFAULT 'SECRETARIA PROVINCIAL & ATOS CANÔNICOS',
  lema_oficial text NOT NULL DEFAULT '«COR JESU, IN TE CONFIDO • SINT UNUM»',
  email_secretaria text NOT NULL DEFAULT 'secretaria@brm.org.br',
  telefone_secretaria text NOT NULL DEFAULT '(41) 3342-1200',
  notificar_confrade_email boolean NOT NULL DEFAULT true,
  notificar_secretario_nova_resposta boolean NOT NULL DEFAULT true,
  exibir_marca_dagua boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.secretaria_formularios (
  id text PRIMARY KEY DEFAULT ('form-' || substr(gen_random_uuid()::text, 1, 8)),
  codigo text NOT NULL DEFAULT 'FORM-2026/001',
  titulo text NOT NULL,
  descricao text,
  evento_id text,
  campos jsonb NOT NULL DEFAULT '[]'::jsonb,
  ativo boolean NOT NULL DEFAULT true,
  limite_vagas integer,
  prazo_encerramento text,
  mensagem_sucesso text,
  total_respostas integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.secretaria_respostas_formulario (
  id text PRIMARY KEY DEFAULT ('resp-' || substr(gen_random_uuid()::text, 1, 8)),
  formulario_id text NOT NULL,
  evento_id text,
  dados jsonb NOT NULL DEFAULT '{}'::jsonb,
  protocolo text NOT NULL,
  status text NOT NULL DEFAULT 'Confirmada',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================
-- PARTE 4: ÍNDICES E POLÍTICAS RLS (SEGURANÇA DA INFORMAÇÃO)
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_usuarios_auth_user_id ON public.usuarios(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_hospedagens_motivo ON public.hospedagens(hos_estadiamotivo);
CREATE INDEX IF NOT EXISTS idx_hospedagens_modulo ON public.hospedagens(hos_modulo);
CREATE INDEX IF NOT EXISTS idx_hospedagens_status ON public.hospedagens(hos_status);
CREATE INDEX IF NOT EXISTS idx_obras_comunidade ON public.obras(comunidade_id);
CREATE INDEX IF NOT EXISTS idx_religiosos_comunidade ON public.religiosos(comunidade_atual_id);
CREATE INDEX IF NOT EXISTS idx_religiosos_obra ON public.religiosos(obra_atual_id);
CREATE INDEX IF NOT EXISTS idx_religiosos_nome ON public.religiosos(nome_civil);

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.confighospedagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mainhospedagem ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hos_quartos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statushospedagem ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lavanderia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospedagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.religiosos_obras_referencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentos_provinciais ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_provinciais ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.secretaria_configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.secretaria_formularios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.secretaria_respostas_formulario ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS para acesso público e autenticado
DO $$
BEGIN
  -- confighospedagens
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'confighospedagens' AND policyname = 'confighospedagens_select_all') THEN
    CREATE POLICY "confighospedagens_select_all" ON public.confighospedagens FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'confighospedagens' AND policyname = 'confighospedagens_all_authenticated') THEN
    CREATE POLICY "confighospedagens_all_authenticated" ON public.confighospedagens FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  -- mainhospedagem
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mainhospedagem' AND policyname = 'mainhospedagem_select_all') THEN
    CREATE POLICY "mainhospedagem_select_all" ON public.mainhospedagem FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mainhospedagem' AND policyname = 'mainhospedagem_anon_crud') THEN
    CREATE POLICY "mainhospedagem_anon_crud" ON public.mainhospedagem FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- modulos
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'modulos' AND policyname = 'modulos_select_all') THEN
    CREATE POLICY "modulos_select_all" ON public.modulos FOR SELECT USING (true);
  END IF;

  -- hos_quartos
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'hos_quartos' AND policyname = 'hos_quartos_select_all') THEN
    CREATE POLICY "hos_quartos_select_all" ON public.hos_quartos FOR SELECT USING (true);
  END IF;

  -- statushospedagem
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'statushospedagem' AND policyname = 'statushospedagem_select_all') THEN
    CREATE POLICY "statushospedagem_select_all" ON public.statushospedagem FOR SELECT USING (true);
  END IF;

  -- lavanderia
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'lavanderia' AND policyname = 'lavanderia_select_all') THEN
    CREATE POLICY "lavanderia_select_all" ON public.lavanderia FOR SELECT USING (true);
  END IF;

  -- hospedagens
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'hospedagens' AND policyname = 'hospedagens_insert_anon') THEN
    CREATE POLICY "hospedagens_insert_anon" ON public.hospedagens FOR INSERT TO anon WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'hospedagens' AND policyname = 'hospedagens_select_anon') THEN
    CREATE POLICY "hospedagens_select_anon" ON public.hospedagens FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'hospedagens' AND policyname = 'hospedagens_all_authenticated') THEN
    CREATE POLICY "hospedagens_all_authenticated" ON public.hospedagens FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  -- religiosos_obras_referencia
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'religiosos_obras_referencia' AND policyname = 'religiosos_obras_anon_update_token') THEN
    CREATE POLICY "religiosos_obras_anon_update_token" ON public.religiosos_obras_referencia FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- documentos_provinciais
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'documentos_provinciais' AND policyname = 'documentos_provinciais_all') THEN
    CREATE POLICY "documentos_provinciais_all" ON public.documentos_provinciais FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- eventos_provinciais
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'eventos_provinciais' AND policyname = 'eventos_provinciais_all') THEN
    CREATE POLICY "eventos_provinciais_all" ON public.eventos_provinciais FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- secretaria_configuracoes
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'secretaria_configuracoes' AND policyname = 'secretaria_configuracoes_all') THEN
    CREATE POLICY "secretaria_configuracoes_all" ON public.secretaria_configuracoes FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- secretaria_formularios
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'secretaria_formularios' AND policyname = 'secretaria_formularios_all') THEN
    CREATE POLICY "secretaria_formularios_all" ON public.secretaria_formularios FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- secretaria_respostas_formulario
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'secretaria_respostas_formulario' AND policyname = 'secretaria_respostas_formulario_all') THEN
    CREATE POLICY "secretaria_respostas_formulario_all" ON public.secretaria_respostas_formulario FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Storage Bucket para Fotos das Obras
INSERT INTO storage.buckets (id, name, public)
VALUES ('obras-fotos', 'obras-fotos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'obras_fotos_public_read') THEN
    CREATE POLICY obras_fotos_public_read ON storage.objects FOR SELECT TO public USING (bucket_id = 'obras-fotos');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'obras_fotos_anon_insert') THEN
    CREATE POLICY obras_fotos_anon_insert ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'obras-fotos');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'obras_fotos_anon_update') THEN
    CREATE POLICY obras_fotos_anon_update ON storage.objects FOR UPDATE TO anon, authenticated USING (bucket_id = 'obras-fotos') WITH CHECK (bucket_id = 'obras-fotos');
  END IF;
END $$;

-- =============================================================
-- PARTE 5: POPOULAÇÃO INICIAL DE DADOS (SEED DATA)
-- =============================================================

-- Configurações de Hospedagem
INSERT INTO public.confighospedagens (
  idconfighospedagens, chos_acolhida, chos_ativar, chos_txtinativo, chos_visiveis, chos_invisiveis
) VALUES (
  1, 'Seja bem-vindo(a)! Província BRM.', 'ativo',
  'As inscrições estão suspensas no momento.',
  '["categoria", "nome", "nascimento", "cpfrg", "email", "telefone", "telefoneemergencia", "endereco", "alergico", "restricao", "lavanderia", "estadiamotivo", "modulo", "previsao", "recibo", "termo"]'::jsonb,
  '[]'::jsonb
) ON CONFLICT (idconfighospedagens) DO UPDATE SET chos_acolhida = excluded.chos_acolhida;

INSERT INTO public.mainhospedagem (main_motivo, main_mensagemtela, main_mensagememail, main_termos, main_status)
VALUES ('Retiro de Formação', 'Sua inscrição foi recebida com sucesso.', 'Recebemos sua inscrição com sucesso.', 'Eu aceito os termos da hospedagem.', 'Ativo')
ON CONFLICT DO NOTHING;

INSERT INTO public.modulos (mod_nome, mod_status) VALUES ('Módulo 1', 'Ativo'), ('Módulo 2', 'Ativo') ON CONFLICT DO NOTHING;
INSERT INTO public.hos_quartos (hos_qua_nome, hos_qua_status) VALUES ('Quarto 01', 'Ativo'), ('Quarto 02', 'Ativo') ON CONFLICT DO NOTHING;
INSERT INTO public.statushospedagem (sta_nome, sta_status) VALUES ('Pendente', 'Ativo'), ('Confirmada', 'Ativo'), ('Check-in', 'Ativo'), ('Check-out', 'Ativo') ON CONFLICT DO NOTHING;
INSERT INTO public.lavanderia (lav_servico) VALUES ('Lavagem e Passadoria Padrão'), ('Apenas Roupa de Cama e Banho') ON CONFLICT DO NOTHING;

-- Configurações Iniciais da Secretaria
INSERT INTO public.secretaria_configuracoes (
  id, prefixo_decretos, numero_atual_decretos, prefixo_portarias, numero_atual_portarias,
  prefixo_circulares, numero_atual_circulares, prefixo_formularios, numero_atual_formularios,
  cabecalho_institucional, subtitulo_provincia, orgao_emissor, lema_oficial,
  email_secretaria, telefone_secretaria, notificar_confrade_email,
  notificar_secretario_nova_resposta, exibir_marca_dagua
) VALUES (
  'default-secretaria-cfg', 'DEC-BRM', 14, 'PORT-BRM', 8,
  'CIRC-BRM', 5, 'FORM-BRM', 3,
  'CONGREGAÇÃO DOS PADRES DO SAGRADO CORAÇÃO DE JESUS',
  'PROVÍNCIA BRASIL MERIDIONAL (SCJ) • CURIA PROVINCIAL',
  'SECRETARIA PROVINCIAL & ATOS CANÔNICOS',
  '«COR JESU, IN TE CONFIDO • SINT UNUM»',
  'secretaria@brm.org.br', '(41) 3342-1200', true, true, true
) ON CONFLICT (id) DO UPDATE SET updated_at = now();

-- Paróquias, Casas e Obras da Província BRM
INSERT INTO public.religiosos_obras_referencia (
  nome, tipo, cidade, localidade, uf, email, telefone, diocese, fundacao, endereco, instagram, facebook, youtube, site, status
) VALUES
  ('Santuário Santa Rita de Cássia', 'Paróquia', 'Curitiba', 'Curitiba', 'PR', 'contato@santuariosantaritadecassia.com.br', '41 3276-2075', 'Arquidiocese de Curitiba', '1960-05-22', 'R. Padre Dehon, 728 - Hauer | Curitiba-PR', 'https://www.instagram.com/santaritacuritiba', 'https://www.facebook.com/santaritacuritiba', 'https://www.youtube.com/@tvdasrosas', 'https://www.santuariosantaritadecassia.com.br/', 'Ativa'),
  ('Santuário São Judas Tadeu', 'Paróquia', 'Curitiba', 'Curitiba', 'PR', 'santuariosjtadeu@gmail.com', '41 3276-4021', 'Arquidiocese de Curitiba', '2010-03-01', 'R. Carlos de Laet, 2495 - Hauer | Curitiba-PR', 'https://www.instagram.com/saojudascuritiba/', 'https://www.facebook.com/SaoJudasCuritiba/', 'https://www.youtube.com/@santuariosaojudastadeu-hau4636', '', 'Ativa'),
  ('Imaculada Conceição', 'Paróquia', 'Mangueirinha', 'Mangueirinha', 'PR', 'paroquiamang@hotmail.com', '46 3243-1226', 'Diocese de Palmas-Francisco Beltrão', '1971-12-08', 'Rua Governador Trotta, 123 | Mangueirinha-PR', 'https://www.instagram.com/imaculadaconceicaomangueirinha/', 'https://www.facebook.com/imaculaconceicaomangueirinha', 'https://www.youtube.com/@paroquiaimaculada33', '', 'Ativa'),
  ('Nossa Senhora Aparecida', 'Paróquia', 'Palmas', 'Palmas', 'PR', 'aparecidapalmas@live.com', '46 3263-1334', 'Diocese de Palmas-Francisco Beltrão', '2012-03-03', 'Av. Pres Getúlio Vargas, 20 | Palmas-PR', 'https://www.instagram.com/paroquiaaparecidapalmas/', 'https://www.facebook.com/nsapalmas', '', '', 'Ativa'),
  ('Rainha dos Apóstolos', 'Paróquia', 'Ariquemes', 'Ariquemes', 'RO', 'paroquiarainhadosapostolos@hotmail.com', '69 3536-0481', 'Arquidiocese de Porto Velho', '2012-03-03', 'R. Distrito Federal, 3784 | Ariquemes-RO', 'https://www.instagram.com/rainhadosapostolosparoquia/', 'https://web.facebook.com/rainhadosapostolosparoquia/', 'https://www.youtube.com/@paroquiarainhadosapostolosro', '', 'Ativa'),
  ('São Sebastião', 'Paróquia', 'Ji-Paraná', 'Ji-Paraná', 'RO', 'paroquiasaosebastiaojipa@gmail.com', '69 3416-4220', 'Diocese de Ji-Paraná', '1984-11-28', 'Rua das Pedras, 265 | Ji-Paraná-RO', 'https://www.instagram.com/pascomsaosebastiaojipa/', 'https://web.facebook.com/pascomcssoficial/', 'https://www.youtube.com/@ParoquiaSaoSebastiaojipa', '', 'Ativa'),
  ('Nossa Senhora de Nazaré', 'Paróquia', 'Porto Velho', 'Porto Velho', 'RO', 'administrativo@paroquiansnazare.org', '69 3227- 0163', 'Arquidiocese de Porto Velho', '2010-02-12', 'R. Pau Ferro, 650 | Porto Velho-RO', 'https://www.instagram.com/paroquianazare_/', 'https://web.facebook.com/p/Paróquia-Nossa-Senhora-de-Nazaré-Porto-Velho-61556544278325/', 'https://www.youtube.com/@paroquianossasenhoradenaza474', '', 'Ativa'),
  ('São José', 'Paróquia', 'Boa Vista do Buricá', 'Boa Vista do Buricá', 'RS', 'paroquiasaojosebvb@yahoo.com.br', '55 3538-1290', 'Diocese de Santo Ângelo', '1940-12-15', 'Av. São José, 805 | Boa Vista do Buricá-RS', 'https://www.instagram.com/paroquiasaojosebvb/', 'https://web.facebook.com/BVBsaojoseParoquia/', 'https://www.youtube.com/@ParóquiaSãoJosé-BVB', '', 'Ativa'),
  ('Paróquia Sagrado Coração de Jesus', 'Paróquia', 'Porto Xavier', 'Porto Xavier', 'RS', 'scjpx@hotmail.com', '55 3354-1066', 'Diocese de Santo Ângelo', '1964-01-26', 'Rua Júlio de Castilhos, 635 | Porto Xavier-RS', 'https://www.instagram.com/pascomsagcoracaodejesus', 'https://web.facebook.com/p/Pascom-Porto-Xavier-100008254681626/', '', '', 'Ativa'),
  ('Nossa Senhora Aparecida', 'Paróquia', 'Tuparendi', 'Tuparendi', 'RS', 'paroquia.aparecidatup@gmail.com', '55 3543-1179', 'Diocese de Santo Ângelo', '1963-04-09', 'Avenida Uruguai, 2149 | Tuparendi-RS', 'https://www.instagram.com/aparecida.1963/', 'https://web.facebook.com/aparecidatuparendi', 'https://www.youtube.com/@paroquiatuparendi', '', 'Ativa'),
  ('São Pedro Apóstolo', 'Paróquia', 'Armazém', 'Armazém', 'SC', 'paroquiasp@yahoo.com.br', '48 3645-0142', 'Diocese de Tubarão', '1940-12-21', 'Praça Dois Corações, 80 | Armazém-SC', 'https://www.instagram.com/paroquiasaopedroazm/', 'https://web.facebook.com/igrejasaopedroapostolo/', 'https://www.youtube.com/@paroquiasaopedroapostoloaz3611', '', 'Ativa'),
  ('São José', 'Paróquia', 'Botuverá', 'Botuverá', 'SC', 'saojosepbotuvera@gmail.com', '47 3359-1142', 'Arquidiocese de Florianópolis', '1912-12-26', 'Rua Padre Carlos Enderlin, 215 | Botuverá-SC', 'https://www.instagram.com/paroquiasaojosebotuvera/', 'https://www.facebook.com/paroquia.sao.jose.249798/', 'https://www.youtube.com/@ParoquiaSãoJoséBotuverá', '', 'Ativa'),
  ('São Luiz Gonzaga', 'Paróquia', 'Brusque', 'Brusque', 'SC', 'secretaria@paroquiasaoluisgonzaga.com', '47 3351-1258', 'Arquidiocese de Florianópolis', '1904-10-04', 'R. Padre Gatone, 75 | Brusque-SC', 'https://www.instagram.com/matrizsaoluisgonzaga/', 'https://www.facebook.com/matrizsaoluisgonzaga/', 'https://www.youtube.com/@paroquiasaoluisgonzaga-bru1666', 'https://www.paroquiasaoluisgonzaga.com/', 'Ativa'),
  ('São José', 'Paróquia', 'Corupá', 'Corupá', 'SC', 'psec11@arquijoinville.com.br', '47 3375-1166', 'Arquidiocese de Joinville', '1928-03-19', 'R. Padre Vicente Schmitz, 116 | Corupá-SC', 'https://www.instagram.com/paroquiasaojose.corupa/', 'https://www.facebook.com/paroquiasaojosecorupa/#', '', '', 'Ativa'),
  ('Santuário Sagrado Coração de Jesus', 'Paróquia', 'Gravatal', 'Gravatal', 'SC', 'p.gravatal@diocesetb.org.br', '48 3642-2121', 'Diocese de Tubarão', '1966-01-30', 'R. Otacílio C. Duarte, 118 | Gravatal-SC', 'https://www.instagram.com/santuarioscj.gravatal/', 'https://web.facebook.com/santuariogravatal/', 'https://www.youtube.com/@santuarioscj.gravatal', 'https://www.psscj.org.br/', 'Ativa'),
  ('Nossa Senhora do Perpétuo Socorro', 'Paróquia', 'Guabiruba', 'Guabiruba', 'SC', 'igrejaguabiruba@gmail.com', '47 3354-0115', 'Arquidiocese de Florianópolis', '1963-03-19', 'Rua Brusque, 09 | Guabiruba-SC', 'https://www.instagram.com/paroquia.guabiruba/', 'https://www.facebook.com/NossaSenhoradoPerpetuoSocorroGuabiruba', 'https://www.youtube.com/@paroquia.guabiruba', 'https://paroquiaguabiruba.org.br/', 'Ativa'),
  ('São Cristóvão', 'Paróquia', 'Itajaí', 'Itajaí', 'SC', 'secretaria@paroquiasaocristovao.com', '47 3341-1408', 'Arquidiocese de Florianópolis', '2011-01-29', 'Rua Odílio García, 456 | Itajaí-SC', 'https://www.instagram.com/paroquiasaocristovaoitj/', 'https://www.facebook.com/paroquiasaocristovaoitj', 'https://www.youtube.com/@paroquiasaocristovaoitj', 'https://www.paroquiasaocristovao.com/', 'Ativa'),
  ('Nossa Senhora das Graças', 'Paróquia', 'Jaraguá do Sul', 'Jaraguá do Sul', 'SC', 'riocerro@diocesejoinville.com.br', '47 3376-1931', 'Arquidiocese de Joinville', '2004-01-01', 'R. Ângelo Rubini, 1256 | Jaraguá do Sul-SC', 'https://www.instagram.com/paroquia.nsg.jaragua/', 'https://www.facebook.com/paroquia.nsg.jaragua', 'https://www.youtube.com/@paroquia.nsg.jaragua', '', 'Ativa'),
  ('Nossa Senhora do Rosário', 'Paróquia', 'Jaraguá do Sul', 'Jaraguá do Sul', 'SC', 'psec63@arquijoinville.com.br', '47 3276-1002', 'Arquidiocese de Joinville', '1952-08-15', 'R. Pioneiro Luiz Sarti, 1397 | Jaraguá do Sul-SC', 'https://www.instagram.com/paroquia.n.sra.rosario_oficial/', 'https://www.facebook.com/paroquianossasenhoradorosarionereuramos', '', '', 'Ativa'),
  ('São Sebastião', 'Paróquia', 'Jaraguá do Sul', 'Jaraguá do Sul', 'SC', 'psec15@diocesejoinville.com.br', '47 3371-0321', 'Arquidiocese de Joinville', '1912-07-31', 'Av. Mal. Deodoro da Fonseca, 632 | Jaraguá do Sul-SC', 'https://www.instagram.com/matrizsaosebastiao/', 'https://www.facebook.com/matrizsaosebastiao', 'https://www.youtube.com/@paroquiasaosebastiaoscj-pa21', 'https://www.paroquiasaosebastiaoscj.com.br/', 'Ativa'),
  ('Santuário Sagrado Coração de Jesus', 'Paróquia', 'Joinville', 'Joinville', 'SC', 'comunicacao@santuarioscj.com.br', '47 3455-2204', 'Arquidiocese de Joinville', '1917-05-04', 'Rua Inácio Bastos, 308 | Joinville-SC', 'https://www.instagram.com/santuarioscj/', 'https://www.facebook.com/santuarioscj', 'https://www.youtube.com/@santuarioscj8092', 'https://santuarioscj.com.br/', 'Ativa'),
  ('São João Batista', 'Paróquia', 'Rio do Sul', 'Rio do Sul', 'SC', 'contato@catedralderiodosul.com.br', '47 3521-0769', 'Diocese de Rio do Sul', '2014-02-16', 'Rua São João, 154 | Rio do Sul-SC', 'https://www.instagram.com/catedralderiodosul/', 'https://www.facebook.com/catedralderiodosul/', 'https://www.youtube.com/@catedralderiodosul', 'https://catedralderiodosul.com.br/', 'Ativa'),
  ('São Judas Tadeu', 'Paróquia', 'Rio do Sul', 'Rio do Sul', 'SC', 'paroquiasjt@softhouse.com.br', '47 3522-0866', 'Diocese de Rio do Sul', '2008-02-02', 'R. Ana Nery, 500 | Rio do Sul-SC', '', 'https://www.facebook.com/Paroquiasaojudasriodosul/', '', '', 'Ativa'),
  ('Santo Antônio de Pádua', 'Paróquia', 'Rio Negrinho', 'Rio Negrinho', 'SC', 'psec19@diocesejoinville.com.br', '47 3644-2081', 'Arquidiocese de Joinville', '1944-01-01', 'R. Luís Scholz, 175 | Rio Negrinho-SC', 'https://www.instagram.com/santoantoniorionegrinhosc/', 'https://www.facebook.com/santoantoniorionegrinhosc', 'https://www.youtube.com/@santoantoniorionegrinhosc', '', 'Ativa'),
  ('Puríssimo Coração de Maria', 'Paróquia', 'São Bento do Sul', 'São Bento do Sul', 'SC', 'psec20@diocesejoinville.com.br', '47 3633-5057', 'Arquidiocese de Joinville', '1904-10-04', 'Rua Capitão Ernesto Nunes, 220 | São Bento do Sul-SC', 'https://www.instagram.com/purissimocoracaodemaria/', 'https://www.facebook.com/PurissimoCoracaodeMariaSbs/', 'https://www.youtube.com/@paroquiapurissimocoracaode9887', '', 'Ativa'),
  ('São Sebastião', 'Paróquia', 'Vidal Ramos', 'Vidal Ramos', 'SC', 'paroquiass@gmail.com', '47 3356-1134', 'Diocese de Rio do Sul', '1951-01-20', 'Rua Leoberto Leal, 216 | Vidal Ramos-SC', 'https://www.instagram.com/paroquiavidalramos/', 'https://www.facebook.com/paroquiavidalramos', '', '', 'Ativa'),
  ('Seminário São José', 'Casa', 'Rio Negrinho', 'Rio Negrinho', 'SC', 'seminariosaojose@brm.org.br', '47 3644-2099', '', '1949-03-20', 'Rua do Seminário, 245 | Rio Negrinho-SC', 'https://www.instagram.com/seminariosj/', 'https://web.facebook.com/seminariosj', '', '', 'Ativa'),
  ('Convento Sagrado Coração de Jesus', 'Casa', 'Brusque', 'Brusque', 'SC', 'cscj@brm.org.br', '47 3351-1404', '', '1924-06-03', 'R. Padre Leon Dehon, 50 | Brusque-SC', 'https://www.instagram.com/conventoscj/', 'https://web.facebook.com/conventosagradocoracaodejesus/', 'https://www.youtube.com/@ConventoSagradoCoracaodeJesus', '', 'Ativa'),
  ('Noviciado Nossa Senhora de Fátima', 'Casa', 'Jaraguá do Sul', 'Jaraguá do Sul', 'SC', 'noviciado.nsf@gmail.com', '47 3376-0559', '', '1956-02-11', 'R. Padre Aloísio Boeing, 742 | Jaraguá do Sul-SC', 'https://www.instagram.com/noviciadofatima/', 'https://web.facebook.com/noviciadofatima/', 'https://www.youtube.com/@noviciadofatima', '', 'Ativa'),
  ('Seminário SCJ', 'Obra', 'Corupá', 'Corupá', 'SC', 'gerenteseminario@gmail.com', '47 3375-1194', '', '1932-01-17', 'Rua Padre Gabriel Lux, 900 | Corupá-SC', 'https://www.instagram.com/seminario.scj/', 'https://web.facebook.com/seminarioscj/', '', '', 'Ativa'),
  ('Casa Padre Dehon', 'Obra', 'Brusque', 'Brusque', 'SC', 'cpdehon@yahoo.com.br', '47 3351-1906', '', '1982-08-02', 'R. Gilberto Comandolli, 100 | Brusque-SC', 'https://www.instagram.com/casapadredehon/', 'https://web.facebook.com/casapadredehon/', '', '', 'Ativa')
ON CONFLICT (nome, localidade, uf) DO UPDATE SET updated_at = now();

-- Eventos Canônicos da Agenda Provincial 2026
INSERT INTO public.eventos_provinciais (
  id, titulo, tipo, data_inicio, data_fim, horario, local, cidade, uf, descricao, publico_alvo, status, exige_inscricao, formulario_id, limite_vagas, prazo_inscricao
) VALUES
  ('evt-1', 'Retiro Provincial dos Presbíteros (Turma I)', 'Retiro', '2026-03-14', '2026-03-18', '08:00', 'Casa Padre Dehon', 'Brusque', 'SC', 'Retiro anual de espiritualidade dehoniana.', 'Presbíteros', 'Confirmado', true, 'form-retiro-presbiteros-2026', 60, '2026-03-05'),
  ('evt-2', 'Reunião Ordinária do Conselho Provincial', 'Reunião', '2026-04-15', NULL, '09:00', 'Sede Provincial', 'Curitiba', 'PR', 'Sessão com o Superior Provincial e Conselheiros.', 'Governo Provincial', 'Confirmado', false, NULL, NULL, NULL),
  ('evt-3', 'Encontro dos Fratres da Etapa de Configuração (Teologia)', 'Encontro', '2026-05-22', '2026-05-24', '14:00', 'Seminário SCJ', 'Corupá', 'SC', 'Convivência vocacional e partilha pastoral.', 'Fratres', 'Confirmado', true, 'form-encontro-fratres-2026', 30, '2026-05-10'),
  ('evt-4', 'Solenidade do Sagrado Coração de Jesus', 'Celebração / Solenidade', '2026-06-19', NULL, '19:00', 'Todas as Comunidades', 'Curitiba', 'PR', 'Festa titular com renovação dos votos.', 'Toda a Província', 'Confirmado', false, NULL, NULL, NULL),
  ('evt-5', 'Memória do Venerável Pe. Leão João Dehon', 'Celebração / Solenidade', '2026-08-12', NULL, '19:30', 'Todas as Paróquias e Casas', 'Curitiba', 'PR', 'Celebração eucarística em honra ao nosso fundador.', 'Toda a Província', 'Confirmado', false, NULL, NULL, NULL),
  ('evt-6', 'Assembleia Provincial Ordinária 2026', 'Assembleia', '2026-10-05', '2026-10-09', '08:30', 'Seminário São José', 'Rio Negrinho', 'SC', 'Assembleia anual com a presença de todos os confrades.', 'Toda a Província', 'Confirmado', true, 'form-assembleia-provincial-2026', 120, '2026-09-20')
ON CONFLICT (id) DO NOTHING;

-- Formulários da Secretaria Provincial
INSERT INTO public.secretaria_formularios (
  id, codigo, titulo, descricao, evento_id, campos, ativo, limite_vagas, prazo_encerramento, mensagem_sucesso, total_respostas
) VALUES
  (
    'form-retiro-presbiteros-2026', 'FORM-2026/001', 'Inscrição para o Retiro Provincial dos Presbíteros 2026 (Turma I)',
    'Formulário canônico de inscrição para hospedagem, paramentação e logística do Retiro Anual na Casa Padre Dehon (Brusque/SC).', 'evt-1',
    '[
      {"id": "nome_completo", "label": "Nome Civil Completo", "categoria": "Identificação", "obrigatorio": true, "tipo": "text"},
      {"id": "nome_religioso", "label": "Nome Religioso / Tratamento", "categoria": "Identificação", "obrigatorio": true, "tipo": "text"},
      {"id": "grau_ordem", "label": "Grau / Vínculo Canônico", "categoria": "Identificação", "obrigatorio": false, "tipo": "select", "opcoes": ["Padre (Presbítero)", "Diácono", "Frater", "Irmão", "Bispo"]},
      {"id": "comunidade_atual", "label": "Comunidade Atual / Residência", "categoria": "Identificação", "obrigatorio": true, "tipo": "text"},
      {"id": "email", "label": "E-mail Principal", "categoria": "Contato", "obrigatorio": true, "tipo": "email"},
      {"id": "telefone_whatsapp", "label": "Telefone / WhatsApp", "categoria": "Contato", "obrigatorio": true, "tipo": "tel"},
      {"id": "necessita_hospedagem", "label": "Necessita de Hospedagem / Quarto?", "categoria": "Acolhida & Hospedagem", "obrigatorio": true, "tipo": "select", "opcoes": ["Sim", "Não"]},
      {"id": "tipo_quarto", "label": "Tipo de Acomodação Desejada", "categoria": "Acolhida & Hospedagem", "obrigatorio": false, "tipo": "select", "opcoes": ["Individual", "Duplo", "Térreo / Acessível"]},
      {"id": "restricao_alimentar", "label": "Restrição Alimentar ou Alergia", "categoria": "Saúde & Alimentação", "obrigatorio": false, "tipo": "text"},
      {"id": "tamanho_paramento", "label": "Tamanho de Paramento / Túnica", "categoria": "Liturgia & Geral", "obrigatorio": false, "tipo": "select", "opcoes": ["P", "M", "G", "GG", "Sob medida"]}
    ]'::jsonb, true, 60, '2026-03-05', 'Inscrição recebida pela Secretaria Provincial. A hospedaria já foi comunicada.', 2
  ),
  (
    'form-assembleia-provincial-2026', 'FORM-2026/002', 'Confirmação de Presença na Assembleia Provincial Ordinária 2026',
    'Confirmação obrigatória de participação com definição de transporte e alojamento no Seminário São José (Rio Negrinho/SC).', 'evt-6',
    '[
      {"id": "nome_completo", "label": "Nome Civil Completo", "categoria": "Identificação", "obrigatorio": true, "tipo": "text"},
      {"id": "nome_religioso", "label": "Nome Religioso / Tratamento", "categoria": "Identificação", "obrigatorio": true, "tipo": "text"},
      {"id": "comunidade_atual", "label": "Comunidade Atual / Residência", "categoria": "Identificação", "obrigatorio": true, "tipo": "text"},
      {"id": "email", "label": "E-mail Principal", "categoria": "Contato", "obrigatorio": true, "tipo": "email"},
      {"id": "telefone_whatsapp", "label": "Telefone / WhatsApp", "categoria": "Contato", "obrigatorio": true, "tipo": "tel"}
    ]'::jsonb, true, 120, '2026-09-20', 'Sua confirmação para a Assembleia Provincial 2026 foi registrada.', 0
  )
ON CONFLICT (id) DO NOTHING;

-- Notificação de Sucesso
SELECT 'Banco de Dados da Província BRM configurado com sucesso no Supabase!' AS resultado;
