begin;

alter table public.religiosos
  add column if not exists numero_cadastro bigint generated by default as identity;

create unique index if not exists religiosos_numero_cadastro_uidx
  on public.religiosos (numero_cadastro);

commit;
